from PySide6.QtWidgets import QMessageBox
import re

def show_invalid_file_dialog(self, title, text):
    msg = QMessageBox(self)
    msg.setIcon(QMessageBox.Warning)
    msg.setWindowTitle(title)
    msg.setText(text)
    msg.setStandardButtons(QMessageBox.Ok)
    msg.exec()

def show_info_dialog(self, title, text):
    msg = QMessageBox(self)
    msg.setIcon(QMessageBox.Information)
    msg.setWindowTitle(title)
    msg.setText(text)
    msg.setStandardButtons(QMessageBox.Ok)
    msg.exec()

def clean_ocr_text(text):
    """
    Aggressively clean OCR text for any document type while preserving
    meaningful words, numbers, dates, grades, and key phrases.
    """

    # Normalize whitespace
    text = " ".join(text.split())

    # Remove repeated symbols (e.g., ----====, X-X-X-X)
    text = re.sub(r'([^\w\s])(?:\1[-\1]*){3,}', ' ', text)

    # Remove sequences of symbols that are likely garbage (≥5 chars)
    text = re.sub(r'\b[^\w\s]{5,}\b', ' ', text)

    # Remove very short nonsense tokens (1-2 chars of symbols only)
    text = re.sub(r'\b[^\w\s]{1,2}\b', ' ', text)

    # Remove stray punctuation surrounded by whitespace (like " , " or " ; ")
    text = re.sub(r'\s[^\w\s]\s', ' ', text)

    # Remove multiple consecutive non-alphanumeric symbols inside words
    text = re.sub(r'(?<=\w)[^\w\s]{2,}(?=\w)', '', text)

    # Remove stray non-printable/control characters
    text = re.sub(r'[\x00-\x1F\x7F]', '', text)

    # Final cleanup: collapse multiple spaces
    text = " ".join(text.split())

    return text

def label_to_type(labels):
    label_map = {
        "201file": "201 File",
        "BOTapproval": "BOT Approval",
        "Mreceipt": "Material Requisition",
        "Notice": "Notice",
        "Requirements_Procedures_Guidelines": "Requirements/Procedures/Guidelines",
        "Narrativereport": "Narrative Report",
        "Notice": "Notice",
        "accomplishments": "Accomplishment Report",
        "acknowform": "Acknowledgment Form",
        "actionresearch": "Action Research",
        "admissform": "Admission Form",
        "agreement": "Agreement",
        "amenitiespwd": "Amenities for Person with Disability",
        "appletter": "Application Letter",
        "application": "Application Letter",
        "appoint": "Appointment",
        "appointment": "Appointment",
        "appresearchpatent": "Application for Research Patent",
        "approvaloffice": "Approval",
        "approvedOTwopay": "Approved Overtime Without Pay",
        "assessmentform": "Assessment Form",
        "assessmentreport": "Assessment Report",
        "attendance": "Attendance",
        "awards": "Award",
        "actionplan": "Action Plan",
        "administrative": "Administrative Manual",
        "advertisementhiring": "Advertisment of Hiring",
        "agencyrequest": "Agency Request",
        "announcement": "Announcement",
        "app": "Approval",
        "approval": "Approval",
        "assessmentprogram": "Assessment Program",
        "attend": "Certificate of Attendance",
        "award": "Award",
        "banktransac": "Bank Transaction",
        "bulletininfomaterials": "Bulletin Of Information",
        "benchmarksurvey": "Benchmark Survey Result",
        "biodata": "Biodata",
        "borrowerslip": "Borrower Slip",
        "brgymnginfo": "Barangay Management Information System",
        "budgetallocutil": "Budget Allocation and Utilization",
        "buildcode": "Building Code",
        "career": "Career Counseling Programs",
        "cert": "Certificate of Recognition",
        "certacceptance": "Certificate of Acceptance",
        "certcopyright": "Certificate of Copyright",
        "certemployment": "Certificate of Employment",
        "certenrollment": "Certificate of Enrollment",
        "certofappearance": "Certificate of Appearance",
        "certofcash": "Certificate of Cash Incentive",
        "certofmembership": "Certificate of Membership",
        "certofparticipation": "Certificate of Participation",
        "certoftraining": "Certificate of Training",
        "chedro": "Reports to CHEDRO",
        "citizencharter": "Citizens Charter",
        "classobserve": "Classroom Observation",
        "cofservice": "Certificate of Service",
        "collectionpolicy": "Collection Development Policy Statement",
        "collegecode": "College Code",
        "collegesyllabi": "Course Syllabi",
        "consultation": "Consultation Programs",
        "confirmationletter": "Confirmation Letter",
        "coursesyllabus": "Course Syllabus",
        "criteria": "Criteria",
        "canteen": "Canteen Menu",
        "canteenmenu": "Canteen Menu",
        "careercoun": "Career Counseling Programs",
        "catalogs": "Catalog",
        "certenrollment": "Certificate of Enrollment",
        "certificateofoccupancy": "Certificate of Occupancy",
        "certmatriculation": "Certificate of Matriculation",
        "certofcalibration": "Certificate of Calibration",
        "certofdisbursement": "Certificate of Disbursement",
        "certofmedteam": "Certification by Medical Team",
        "certoftitle": "Certificate of Title",
        "chedcmo": "CHED CMO",
        "chedls": "CHED LS",
        "citizen": "Citizens Charter",
        "class": "Classroom Observation",
        "classrec": "Class Record",
        "classutil": "Classroom Utilization",
        "code": "College Code",
        "codeconduct": "Code of Conduct for Foreign Students",
        "codeofethicstandards": "Code of Ethical Standards",
        "communications": "Communications",
        "compcommittee": "Composition of Committee",
        "compcommittees": "Composition of Committee",
        "compisyllabi": "Compilation of Syllabi ",
        "comprofile": "Community Profile",
        "compspecs": "Computer Specification",
        "constbylaws": "Constitution and By-Laws",
        "copyprog": "Copy of Program",
        "courseoutline": "Course Outline",
        "coursesyllabi": "Course Syllabi",
        "cscpub": "CSC Publication",
        "currentawareness": "Current Awareness",
        "currichecklist": "Curriculum Checklist",
        "curriculum": "Curriculum",
        "curriculumvitae": "Curriculum Vitae",
        "currimatrix": "Curriculum Matrix",
        "cv": "Curriculum Vitae",
        "diploma": "Diploma",
        "dtr": "Daily Time Record",
        "dutiesandresponsibilities": "Duties and Responsibilities",
        "deliveryslips": "Delivery Slip",
        "departmental": "Departmental Report",
        "deptchair": "Department Chair/Dean Supervisory Plan",
        "developmentplan": "Development Plan",
        "disbursement": "Certificate of Disbursement",
        "docuprompt": "Documents showing prompt attention to student requests",
        "drillreport": "Drill Report",
        "employmentrecord": "Employment Record",
        "entranceform": "Entrance Application Form",
        "evalform": "Evaluation/Screening Form",
        "expandtraining": "Related Experiences and Trainings Attended",
        "elecresource": "Electronic Resource",
        "eligibilityrating": "Eligibility Rating",
        "enrollgradtrend": "Enrollment and Graduation Trend",
        "enrollment": "Enrollment Data",
        "enrollmentdata": "Enrollment Data",
        "equipinv": "Equipment Inventory",
        "evaluative": "Evaluative Measures",
        "evaluativemeasures": "Evaluative Measures",
        "expenditure": "Expenditure",
        "extprogplan": "Extension Program Plan",
        "facultypromotion": "Faculty Promotion",
        "faculty": "List of Faculty",
        "facultymanual": "Faculty Manual",
        "facultyprof": "Faculty Profile",
        "facultyworkload": "Faculty Workload",
        "financial": "Financial Plan",
        "financialplan": "Financial Plan",
        "financialstatement": "Financial Statement",
        "functions": "Function",
        "gradesofsheet": "Grades",
        "gantt": "Gantt Chart",
        "genappact": "General Appropriations Act",
        "grad": "Graduate Employment Profile",
        "grades": "Grades",
        "gradingsystem": "Grading System",
        "graduated": "Graduate Employment Profile",
        "guidanceprog": "Guidance Program",
        "guidancerecord": "Guidance Record",
        "honorabledismissal": "Files of Honorable Dismissal",
        "hire": "Advertisment of Hiring",
        "ipcr": "Indivudual Performance Commitment Review",
        "impactassessment": "Impact Assessment",
        "incomeexpen": "Income and Expenditure Plan",
        "infodrive": "Information Drive",
        "inhousesectoral": "In-House/Sectoral Review",
        "inspectionreport": "Inspection Report",
        "instipopu": "Institute Population",
        "instructmat": "Instructional Material",
        "insurancepolicy": "Insurance Policy",
        "interform": "Interview Form",
        "interview eval": "Result of Interview",
        "interviewevaluation": "Result of Interview",
        "invalid": "",
        "invitationletter": "Invitation Letter",
        "itenarytravel": "Itinerary of Travel",
        "janitorialstaff": "Janitorial Staff",
        "journalpub": "Journal of Publication",
        "laws": "Laws",
        "ledgercard": "Supply Ledger Card",
        "legalbasis": "Legal Basis",
        "lessons": "Lesson",
        "lib": "Library Goals and Objectives",
        "license": "License",
        "listfaculty": "List of Faculty",
        "logbook": "Logbook",
        "lab": "Safety Tips",
        "letter": "Letter",
        "librarygoal": "Library Goals and Objectives",
        "manual": "Manual",
        "medicalrecord": "Medical Record",
        "memo": "Memo",
        "minutes": "Minutes of the Meeting",
        "mandate": "Mandate of the Institution",
        "manual": "Manual",
        "meddental": "Medical and Dental Programs",
        "medmission": "Medical Mission to Different Colleges",
        "meetingagenda": "Meeting Agenda",
        "moa": "Contract/Memorandum of Agreement",
        "monitorandeval": "Result of Monitoring and Evaluation",
        "monitoring": "Result of Monitoring and Evaluation",
        "monitoringandevaluation": "Result of Monitoring and Evaluation",
        "nbc461": "NBC 461",
        "numofdropout": "Number of Drop-outs per Semester/Year",
        "natdevgoals": "National Development Goals",
        "nbc46": "NBC 461",
        "newsletters": "Newsletters",
        "number": "Average number of visitors/patients per day",
        "numberofpatients": "Average number of visitors/patients per day",
        "numofequipment": "Number of Equipment",
        "ojt": "Result of OJT Evaluation",
        "orgchart10": "Organizational Chart",
        "objprog": "Objectives of the Program",
        "observation": "Observation Form",
        "occupancy": "Certificate of Occupancy",
        "ojt/pt": "Result of OJT Evaluation",
        "orgchart": "Organizational Chart",
        "orientprog": "Orientation Program",
        "pds": "Personal Data Sheet",
        "policy": "Policy",
        "programinvitation": "Program Invitation",
        "projectproposal": "Project Proposal",
        "proofbystudent": "Proof of Utilized Research",
        "purchaseorder": "Purchase Order",
        "purchaserequest": "Purchase Request",
        "pyroll": "Payroll",
        "pay": "Payroll",
        "payroll": "Payroll",
        "pbb": "Performance Based Bonus",
        "perfevalsys": "Performance Evaluation System",
        "performanceassessment": "Student Performance Assessment Tools Used",
        "perforreport": "Performance Report on Board Examination by PRC",
        "permit": "Permit",
        "philegps": "Phil-GEPS System",
        "posdescriptionforms": "Position Description Forms",
        "procurementplan": "Procurement Plan",
        "procurementreport": "Procurement Report",
        "procurementworkflow": "Procurement Workflow",
        "procuremngtsys": "Procurement Management System",
        "profofbene": "Profile of Beneficiary of Extension Program",
        "progactivity": "Program of Activity",
        "progawards": "Program of Awards and Recognition",
        "proginvitation": "Program Invitation",
        "progofwork": "Program of Work",
        "progplan": "Program Plan",
        "programofawardsandrecognition": "Program of Awards and Recognition",
        "progreportsext": "Progress Report",
        "progreportsexts": "Progress Reports",
        "proof": "Proof of Utilized Research",
        "psychtests": "Psychological Tests Administered and Results",
        "pt": "Result of OJT Evaluation",
        "pubresearch": "Research Output and Publication",
        "qualicontrieval": "Qualitative Contribuition Evaluation",
        "researchagenda": "Research and Extension Agenda",
        "resolution": "Resolution",
        "ra91": "RA 9184",
        "ra9184": "RA 9184",
        "rapidrural": "Rapid Rural Appraisal Result",
        "recacads": "Records of Academic Achievement of Students",
        "receipt": "Receipt",
        "recordbook": "Record Book",
        "recordsystem": "Record System",
        "reentryplan": "Re-Entry Plan of Faculty after Study Leave",
        "referral": "Referral Form",
        "regisform": "Registration Form",
        "reportbaselinedata": "Report of Baseline Data Used for Institutional Development",
        "request": "Request Letter",
        "requestletter": "Request Letter",
        "researchextagenda": "Research and Extension Agenda",
        "researchmanual": "Research Manual",
        "resultassessment": "Result of Assessment of Student Performance",
        "resultsclassenvi": "Results of Quality of Classroom Environment",
        "resultscreening": "Result of Screening/Selection Process",
        "resultsfeedback": "Result of Feedback",
        "retentionreso": "Retention Resolution",
        "review_revisionevaltools": "Student Performance Assessment Tools Used",
        "rulesandregu": "Rules and Regulation",
        "schelendar": "Schedule/Calendar",
        "studentinfosheet": "Student Personal Information Sheet",
        "syllabi": "Syllabi",
        "sasobjectives": "Objectives of the SAS",
        "schoolactivity": "School Activity",
        "schoolpub": "School Publication",
        "screenform": "Screening Form",
        "semestralprogress": "Progress Report",
        "servicerecord": "Service Record",
        "sitedev": "Site Development Plan",
        "softlicense": "Software License",
        "souvenirprog": "Souvenir Program",
        "statreport": "Statistical Report",
        "strategicmanagerial": "Strategic Managerial Planning Workshop",
        "stratperformance": "Strategic Performance Management System",
        "studentclearance": "Student Clearance",
        "studentevaluation": "Student Evaluation",
        "studentoutput": "Student Output",
        "studentrecord": "Student Record",
        "studhandbook": "Student Handbook",
        "studtrustfund": "Student Trust Fund",
        "suboffwithoutpay": "Subjects Offering without Pay",
        "succode": "SUC Code",
        "summfaculty": "Summary of Faculty",
        "surveyform": "Interview/Survey Form",
        "syllabimatrix": "Syllabi Matrix",
        "symposia": "Symposia",
        "tesdacertification": "TESDA Certification",
        "thesismanuscript": "Thesis Manuscript",
        "tor": "Transcript of Records",
        "tracerstudy": "Tracer Study",
        "travelorder": "Travel Order",
        "vmgo": "College VMGO",
        "workload": "Workload Guidelines",
        "meetingagenda": "Meeting Agenda",
        "financialstatement": "Financial Statement",
        "terminal": "Terminal Report",
        "titlesnonprint": "List of Non-Name",
        "travincentive": "Travel Incentive",
        "unithead": "Unit Head",
        "voucher": "Voucher",
        "waiver": "Waiver",
        "waiverofstudents": "Waiver",
        "yearbook": "Yearbook"
    }

    types = []
    for label in labels:
        types.append(label_map[label])
    return types